##
# Generate with:
#   tomljson markdownlint.config.toml > .markdownlint.json
##

#-------------------------------------------------------------------------------
# NOT APPLIED

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md020.md
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md021.md

#-------------------------------------------------------------------------------
# BOOLEANS

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md005.md
list-indent = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md011.md
no-reversed-links = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md014.md
commands-show-output = false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md018.md
no-missing-space-atx = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md019.md
no-multiple-space-atx = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md023.md
heading-start-left = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md028.md
no-blanks-blockquote = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md032.md
blanks-around-lists = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md034.md
no-bare-urls = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md037.md
no-space-in-emphasis = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md038.md
no-space-in-code = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md039.md
no-space-in-links = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md040.md
fenced-code-language = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md042.md
no-empty-links = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md043.md
required-headings = false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md045.md
no-alt-text = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md047.md
single-trailing-newline = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md056.md
table-column-count = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md058.md
blanks-around-tables = true

#-------------------------------------------------------------------------------
# MAPS

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md001.md
[heading-increment]
front_matter_title = '^\s*(name|title)\s*[:=]'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md003.md
[heading-style]
style = 'atx'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md004.md
[ul-style]
style = 'asterisk'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md007.md
[ul-indent]
indent         = 2.0
start_indent   = 4.0
start_indented = false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md009.md
[no-trailing-spaces]
br_spaces             = 2.0
code_blocks           = false
list_item_empty_lines = false
strict                = false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md010.md
[no-hard-tabs]
code_blocks           = true
ignore_code_languages = []
spaces_per_tab        = 2.0

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md012.md
[no-multiple-blanks]
maximum = 1.0

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
[line-length]
code_blocks = false
headings    = false
line_length = 100000.0
stern       = false
strict      = false
tables      = false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md022.md
[blanks-around-headings]
lines_above = 1.0
lines_below = 1.0

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md024.md
[no-duplicate-heading]
siblings_only = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md025.md
[single-h1]
front_matter_title = '^\s*(name|title)\s*[:=]'
level              = 1.0

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md026.md
[no-trailing-punctuation]
punctuation = '.,;:'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md027.md
[no-multiple-space-blockquote]
list_items = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md029.md
[ol-prefix]
style = 'ordered'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md030.md
[list-marker-space]
ol_multi  = 1.0
ol_single = 1.0
ul_multi  = 1.0
ul_single = 1.0

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md031.md
[blanks-around-fences]
list_items = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md
[no-inline-html]
allowed_elements = [
  # @config-manager:start html_elements
  # @config-manager:end html_elements
]
table_allowed_elements = []

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md035.md
[hr-style]
style = 'consistent'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md036.md
[no-emphasis-as-heading]
punctuation = '.,;:!?'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md041.md
[first-line-h1]
allow_preamble     = true
front_matter_title = '^\s*(name|title)\s*[:=]'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md044.md
[proper-names]
code_blocks = false
html_elements = false
names = [
  # @config-manager:start spelling
  # @config-manager:end spelling
]

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md046.md
[code-block-style]
style = 'fenced'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md048.md
[code-fence-style]
style = 'backtick'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md049.md
[emphasis-style]
style = 'underscore'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md050.md
[strong-style]
style = 'asterisk'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md051.md
[link-fragments]
ignore_case     = false
ignored_pattern = ''

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md052.md
[reference-links-images]
ignored_labels  = ['x']
shortcut_syntax = false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md053.md
[link-image-reference-definitions]
ignored_definitions = ['//']

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md054.md
[link-image-style]
autolink   = true
collapsed  = true
full       = true
inline     = true
shortcut   = true
url_inline = true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md055.md
[table-pipe-style]
style = 'leading_and_trailing'

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md059.md
[descriptive-link-text]
prohibited_texts = ['click here', 'here', 'link', 'more']

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md060.md
[table-column-style]
aligned_delimiter = true
style             = 'aligned'
